name: Execute Script on Pull

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run script
      run: |
        sh ./lib64fix.sh
        sh ./setup install
