name: Execute Script on Push

on:
  push:
    branches:
      - main # Substitua "master" pelo nome da sua branch principal

jobs:
  build:
    runs-on: centos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run script
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x ./lib64fix.sh
        chmod +x ./setup
        sh ./lib64fix.sh
        sh ./setup install
